name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  mobx: ^2.4.0
  google_fonts: ^6.2.1
  floor: ^1.5.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true